### ISSUE TITLE
Data set for model theses80

### ISSUE THREAD

**Issue by hugohn** [zelandiya/keyword-extraction-datasets#1]
First of all, thank you Alyona for this great tool!

Would you happen to have the training data set used to create model 'theses80', that was included in the Maui1.2 download (https://code.google.com/p/maui-indexer/downloads/detail?name=maui1.2_all-incl.tar.gz&can=2)?

Thanks a lot!
~Hugo

**Comment by zelandiya** [comment]
I just uploaded the full dataset: https://github.com/zelandiya/keyword-extraction-datasets/blob/master/theses100.zip But unfortunately, I don't have information about the exact split anymore.

**Comment by hugohn** [comment]
Thank you!
